name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v .
    
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: lab1
        remote: lab1
        host: b1.tnpl.me
        username: azureuser
        password: CRT200858christy
